HTML-Forms
digitekh2i/HTML-Forms pull request #1
Opened 2020-06-21 09:35 UTC by digitekh2i

In this project, I re-created the "intuit.com" sign up page.
-  Standard label form format
- Sign in and Create Account buttons

2020-06-21 11:52 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Hi @digitekh2i 🖐! Awesome project 🎉✨!

### However, we need to work on a couple of issues before we can move on.

- There are some Stylelint errors. Please fix them. From the next time, remember to fix any Styelint errors before requesting for a code review.

![image](https://user-images.githubusercontent.com/57726348/85223100-da4f5d00-b3dd-11ea-90de-b4c208eb0ec8.png)

- You have this PR from `gh-pages`. This branch is normally reserved for creating Github pages and not working on the features of a project. Remember to create a feature branch that has a descriptive name.

- Change the background color of the clone to match the original.

#### Clone

*background-color: #e9f0ea;*
![image](https://user-images.githubusercontent.com/57726348/85223302-b12fcc00-b3df-11ea-867c-69796ec7b57e.png)

#### Original

*background-color: #eceef1;*
![image](https://user-images.githubusercontent.com/57726348/85223284-965d5780-b3df-11ea-8737-dbf5ba1ab4bc.png)

- The phone input field must be of type `tel`, eg., `<input type="tel" ...`.

- The `captcha` part is missing.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85223754-cbb77480-b3e2-11ea-90bf-3bcb4d3e77ce.png)

#### Original
![Annotation 2020-06-21 171546](https://user-images.githubusercontent.com/57726348/85223772-015c5d80-b3e3-11ea-9fa9-fcb53eb399e1.jpg)
Remember to match its background color with the background color of the page.

- The lock icons are missing in the `sign-in` and `create account` buttons.

#### Clone
![Annotation 2020-06-21 171813](https://user-images.githubusercontent.com/57726348/85223840-83e51d00-b3e3-11ea-9d48-a6f980b096e3.jpg)

#### Original
![Annotation 2020-06-21 172001](https://user-images.githubusercontent.com/57726348/85223842-89426780-b3e3-11ea-8057-f606074576a9.jpg)

- There are some invalid CSS properties in your CSS file. Be sure to check the comments below.

2020-06-21 11:54 UTC, tirthajyoti-ghosh commented on style.css
> +margin-right: 150;
Don't forget to add units for your margin values, otherwise, they are deemed invalid by the browser.

2020-06-21 11:56 UTC, tirthajyoti-ghosh reviewed
Apply these changes and request for another review.

Happy coding 👨‍💻

2020-06-22 23:41 UTC, digitekh2i commented
# changelog
- fixed CSS style errors
- changed the background color to fit the original page
- added reCAPTCHA section
- added lock icon to the buttons
- omitted CSS properties that are not in use

# I created a feature branch titled "dev-source" but while trying to update the pull request to compare master -> dev-source, as opposed to master -> gh-pages. I realized that it was doable. the available solution is to create another pull request that would compare master -> dev-source, but it is against the Microverse-Github Workflow. thus, that's why i am re-applying for code review with gh-pages again. Though I have taken corrections from all the feedback.

2020-06-23 00:19 UTC, elmejdki approved these changes
# Great job @digitekh2i :clap: :clap: you have made a great job :tophat: 
### status: approved

now you can merge to master your project has been approved.

### Happy Coding :smiley:

2020-06-23 14:29 UTC, merged